### ISSUE TITLE
code formatting fails

### ISSUE THREAD

**Issue by kayvank** [Baeldung/scala-tutorials#182]
many of the files in the project fail scalafmt check. 
Here is the list of the offenders:
`
/home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-strings/src/test/scala/com/baeldung/scala/strings/interpolation/strings/interpolation/CustomInterpolatorObjTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/ControlStructuresDemoUnitTest.scala isn't formatted properly!
[info] Checking 7 Scala sources...
[info] Checking 1 Scala sources...
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/test/scala/com/baeldung/scala/variance/VarianceUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/main/scala/com/baeldung/scala/underscore/UnderscoreUsages.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-test/src/test/scala/com/baeldung/scala/scalatest/TaggedFlatSpec.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/traits/Score.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/Employee.scala isn't formatted properly!
[info] Checking 1 Scala sources...
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/packageimport/vehicle/Bicycle.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/equality/EqualityTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-test/src/test/scala/com/baeldung/scala/scalatest/ScalaMockFlatSpec.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/test/scala/com/baeldung/scala/classcompositionwithtraits/CarTraitsTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/test/scala/com/baeldung/scala/underscore/UnderscoreUsagesUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-akka/src/test/scala/com/baeldung/scala/akka/typed/PortfolioApplicationUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/main/scala/com/baeldung/scala/variance/Variance.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-akka/src/main/scala/com/baeldung/scala/akka/typed/PortfolioApplication.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/test/scala/com/baeldung/scala/durationsugar/DurationSugarUnitTests.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/mutability/MutableCollectionsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-libraries/src/main/scala/com/baeldung/scala/monocle/OpticsExamples.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/functionsandmethods/FunctionsAndMethods.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-test/src/test/scala/com/baeldung/scala/scalatest/ExampleFlatSpecWithMatchers.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/PatternMatching.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/test/scala/com/baeldung/scala/classvsobject/ObjectExamplesUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/test/scala/com/baeldung/scala/namedanddefaultargs/NamedAndDefaultArgsTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/conditional/ScalaConditionalExpressionsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/forcomprehension/ForLoopUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/mutability/ImmutableCollectionsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/HigherOrderFunctions.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/test/scala/com/baeldung/scala/currency/FutureAndPromiseTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/EmployeeUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/main/scala/com/baeldung/scala/classcompositionwithtraits/CarTraits.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/equality/package.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/ControlStructuresDemo.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/packageimport/vehicle/Car.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/IntSet.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/conditional/ScalaConditionalExpressions.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/test/scala/com/baeldung/scala/classvsobject/ClassExamplesUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/mutability/ImmutabilityCar.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/functionsandmethods/FunctionsAndMethodsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/packageimport/Importing.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/main/scala/com/baeldung/scala/generics/GenericsIntro.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/test/scala/com/baeldung/scala/enumerations/FingersOperationUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/test/scala/com/baeldung/scala/caseclasses/CaseClasses.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/main/scala/com/baeldung/scala/caseobject/ObjectExample.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/lazyval/LazyVal.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/tailrec/StringLength.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-oop/src/main/scala/com/baeldung/scala/enumerations/Fingers.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-lang/src/main/scala/com/baeldung/scala/operators/ScalaOperators.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/main/scala/com/baeldung/scala/forcomprehension/ForComprehension.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/traits/ScoreUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/UtilsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/main/scala/com/baeldung/scala/durationsugar/package.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/forcomprehension/ForLoop.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/main/scala/com/baeldung/scala/Utils.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/main/java/com/baedung/scala/concurrency/FutureAndPromise.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core-2/src/main/scala/com/baeldung/scala/namedanddefaultargs/NamedAndDefaultArgs.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/PatternMatchingUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/HigherOrderFunctionsUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/IntSetUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/HigherOrderFunctionsExamplesUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/lazyval/LazyValUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/sorting/SortingUnitTest.scala isn't formatted properly!
[warn] /home/kayvan/dev/workspaces/workspace-blog/scala-tutorials/scala-core/src/test/scala/com/baeldung/scala/regex/RegexUnitTest.scala isn't formatted properly!
`

**Comment by yadavan88** [comment]
this is already fixed
