### ISSUE TITLE
upgrade to Scala 2.13.x

### ISSUE THREAD

**Issue by kayvank** [Baeldung/scala-tutorials#183]
upgrade to 2.13.x

**Comment by kayvank** [comment]
2.13 supports mapping over [Either](https://www.scala-lang.org/api/current/scala/util/Either.html) among many other enhancements.  This is a critical feature as we start tutorials on [Functors](https://typelevel.org/cats/typeclasses/functor.html), such as the Either Functor

**Comment by yadavan88** [comment]
This is done already, so closing
