### ISSUE TITLE
VSCode doesn't works for scala 3 code base

### ISSUE THREAD

**Issue by khajavi** [Baeldung/scala-tutorials#310]
When I run `sbt launchIDE` , the VSCode (1.51.1) show me this error:

```
Cannot read property 'textDocumentSync' of undefined
```

![image](https://user-images.githubusercontent.com/235974/119254905-272f4b00-bbce-11eb-836c-0d3abf668b62.png)

**Comment by kwoyke** [comment]
Hi @khajavi ,
This seems to be an issue with the VSCode itself. See this GitHub issue for example - https://github.com/microsoft/vscode-jupyter/issues/4976 Looks similar.
I don't think there's much we can do here.
