### ISSUE TITLE
Wrong Example in 

### ISSUE THREAD

**Issue by vasiliy-bout** [Baeldung/scala-tutorials#446]
[Website](https://www.baeldung.com/scala/data-types#4-guarding-against-wrong-conversions) contains the following snippet:
```
val i10 = 127 // Integer 127 
val i11 = 128 // Integer 128 
i11.isValidByte should be (true) 
i10.isValidByte should be (false) 
```
It seems that assertions for `i10` and `i11` are swapped around.

The sources however contain the correct version:
https://github.com/Baeldung/scala-tutorials/blob/c75f4a3494aadcb865461ddf21141874fba7257a/scala-core-3/src/test/scala/com/baeldung/scala/dataTypesAndOps/DatatypesAndOpsUnitTest.scala#L110-L113

**Comment by kwoyke** [comment]
Hi @vasiliy-bout ,
Thanks for catching that! We fixed the article.
